# This file was generated by GoReleaser. DO NOT EDIT.
cask "seon" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "2e43eafb92c836a1dda5ccd3917b61af12a4c6c28ffead30ed4f7d1dd2d0d9fa"
      url "https://github.com/seonNoh/seon-cli-releases/releases/download/v#{version}/seon-darwin-amd64"
      binary "seon-darwin-amd64", target: "seon"
    end
    on_arm do
      sha256 "31a443cfedd63e2c7df24fafb9bffc53c3a40e96aaecc621b01de2f4a324fa50"
      url "https://github.com/seonNoh/seon-cli-releases/releases/download/v#{version}/seon-darwin-arm64"
      binary "seon-darwin-arm64", target: "seon"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4419623bac5326cf4c4fdf261b0b212b0ae7d65a4fcc773821b00c9d9a69777"
      url "https://github.com/seonNoh/seon-cli-releases/releases/download/v#{version}/seon-linux-amd64"
      binary "seon-linux-amd64", target: "seon"
    end
    on_arm do
      sha256 "a448255fe7f50b63b776417e8ea78c00c746a912c2c4672841967ad601bb7963"
      url "https://github.com/seonNoh/seon-cli-releases/releases/download/v#{version}/seon-linux-arm64"
      binary "seon-linux-arm64", target: "seon"
    end
  end

  name "seon"
  desc "Seonology infrastructure management CLI"
  homepage "https://github.com/seonNoh/seon-cli-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

end
